import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
const Font = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["400", "700", '300', '500', '600', '700'],
  variable: "--font-sans",
});

export const metadata = {
  title: "A Healtcare management system",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn}>{children}</body>
    </html>
  );
}
